#!/usr/bin/env python3
"""
Daily Learning Loop — 核心运行脚本

职责：
1. 读取 STATE.md、learning-state.json、最近日报、笔记、研究草稿、复习队列
2. 调用 LLM 生成今日日报、复习题与状态更新
3. 输出到 content/reports/daily/、content/dashboards/、state/、REVIEW-QUEUE.md、STATE.md

注意：本脚本不直接修改 .github/、scripts/、site/、skills/、prompts/、loop-* 文件。
"""

import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

# 项目根目录
REPO_ROOT = Path(__file__).resolve().parent.parent

# 路径常量
STATE_MD = REPO_ROOT / "STATE.md"
STATE_JSON = REPO_ROOT / "state" / "learning-state.json"
REVIEW_QUEUE_MD = REPO_ROOT / "REVIEW-QUEUE.md"
REVIEW_QUEUE_JSON = REPO_ROOT / "state" / "review-queue.json"
NOTES_DIR = REPO_ROOT / "content" / "notes"
RESEARCH_DIR = REPO_ROOT / "content" / "research"
DAILY_DIR = REPO_ROOT / "content" / "reports" / "daily"
DASHBOARDS_DIR = REPO_ROOT / "content" / "dashboards"
PROMPT_FILE = REPO_ROOT / "prompts" / "daily-learning-loop.prompt.md"
SKILL_FILE = REPO_ROOT / "skills" / "daily-learning-triage.md"


def read_file(path: Path) -> str:
    """安全读取文件内容，不存在时返回空字符串。"""
    if path.exists():
        return path.read_text(encoding="utf-8")
    return ""


def write_file(path: Path, content: str) -> None:
    """写入文件，自动创建父目录。"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def get_recent_daily_reports(days: int = 3) -> list[dict]:
    """获取最近 N 天的日报文件列表。"""
    if not DAILY_DIR.exists():
        return []
    files = sorted(DAILY_DIR.glob("*.md"), reverse=True)
    reports = []
    for f in files[:days]:
        reports.append({
            "path": str(f.relative_to(REPO_ROOT)),
            "content": f.read_text(encoding="utf-8") if f.exists() else ""
        })
    return reports


def build_context() -> dict:
    """构建 LLM 调用的完整上下文。"""
    return {
        "state_md": read_file(STATE_MD),
        "state_json": read_file(STATE_JSON),
        "review_queue_md": read_file(REVIEW_QUEUE_MD),
        "review_queue_json": read_file(REVIEW_QUEUE_JSON),
        "recent_reports": get_recent_daily_reports(3),
        "notes_dir_empty": not any(NOTES_DIR.glob("*.md")) if NOTES_DIR.exists() else True,
        "research_dir_empty": not any(RESEARCH_DIR.glob("*.md")) if RESEARCH_DIR.exists() else True,
        "skill": read_file(SKILL_FILE),
        "prompt_template": read_file(PROMPT_FILE),
        "current_date": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
    }


def build_system_prompt(context: dict) -> str:
    """
    组装 system prompt。
    将 prompt 模板中的 {{date}} 替换为当前日期。
    """
    date_str = context["current_date"]
    prompt = context["prompt_template"]
    prompt = prompt.replace("{{date}}", date_str)

    return prompt


def call_llm(system_prompt: str, context: dict) -> str:
    """
    调用 LLM API。
    目前返回模拟输出用于验证流程，后续接入真实 API 调用。

    接入真实 API 时，将 context 中各个字段组装成 API payload。
    """
    date_str = context["current_date"]

    # ================================================================
    # TODO: 替换为真实 LLM 调用
    # 示例：
    #   import openai
    #   response = openai.chat.completions.create(
    #       model="gpt-4",
    #       messages=[
    #           {"role": "system", "content": system_prompt},
    #           {"role": "user", "content": user_message}
    #       ]
    #   )
    #   return response.choices[0].message.content
    # ================================================================

    return f"""# Daily Learning Report — {date_str}

## Summary

This is a placeholder report generated during system initialization.

The system has been set up successfully. Once connected to a real LLM API, this
report will contain actual learning analysis, blind spot detection, and review
task generation.

## Key Findings

- System initialization complete
- Ready for first real learning loop run

## Blind Spots Detected

- (待确认) 需要实际学习数据后才能识别盲区

## Next Steps

1. Configure LLM API key
2. Add initial learning notes to content/notes/
3. Trigger the first real daily learning loop

---

> Generated by Daily Learning Loop on {date_str}
"""


def parse_output(output: str) -> dict:
    """
    解析 LLM 输出，提取变更摘要 JSON。
    如果输出末尾包含 JSON 摘要，则解析并返回；否则返回空摘要。
    """
    # 尝试从输出末尾提取 JSON
    json_match = re.search(r'```json\n(.+?)\n```', output, re.DOTALL)
    if json_match:
        try:
            return json.loads(json_match.group(1))
        except json.JSONDecodeError:
            pass
    return {
        "change_summary": "No structured summary available",
        "files_changed": [],
        "risk_level": "low",
        "new_review_items": 0,
        "archived_items": 0,
        "uncertain_claims": [],
        "sources_used": []
    }


def write_outputs(output: str, context: dict) -> dict:
    """将 LLM 输出写入对应的目标文件。"""
    date_str = context["current_date"]

    # 1. 写入今日日报
    daily_file = DAILY_DIR / f"{date_str}.md"
    write_file(daily_file, output)

    # 2. 写入今日仪表盘（简单提取第一段作为摘要）
    first_line = output.strip().split("\n")[0] if output.strip() else "No content"
    dashboard = f"""# Today's Dashboard

{first_line}

## Quick Stats

- Date: {date_str}
- Status: Report generated

## Recent Activity

{output}
"""
    dashboard_file = DASHBOARDS_DIR / "today.md"
    write_file(dashboard_file, dashboard)

    # 3. 解析变更摘要
    summary = parse_output(output)

    return summary


def validate_outputs() -> bool:
    """调用 validate_outputs.py 验证输出。"""
    import subprocess
    result = subprocess.run(
        [sys.executable, str(REPO_ROOT / "scripts" / "validate_outputs.py")],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(f"Validation failed:\\n{result.stderr}")
        return False
    print("Validation passed.")
    return True


def main():
    """Daily Learning Loop 主流程。"""
    print("=== Daily Learning Loop ===")
    print(f"Time: {datetime.now(timezone.utc).isoformat()}")

    # Step 1: 构建上下文
    print("\\n[1/5] Building context...")
    context = build_context()
    print(f"  Date: {context['current_date']}")
    print(f"  Notes dir empty: {context['notes_dir_empty']}")
    print(f"  Research dir empty: {context['research_dir_empty']}")

    # Step 2: 构建 prompt
    print("\\n[2/5] Building system prompt...")
    system_prompt = build_system_prompt(context)

    # Step 3: 调用 LLM
    print("\\n[3/5] Calling LLM...")
    output = call_llm(system_prompt, context)
    print(f"  Output length: {len(output)} chars")

    # Step 4: 写入输出
    print("\\n[4/5] Writing outputs...")
    summary = write_outputs(output, context)
    print(f"  Files changed: {summary.get('files_changed', [])}")
    print(f"  Risk level: {summary.get('risk_level', 'unknown')}")

    # Step 5: 验证输出
    print("\\n[5/5] Validating outputs...")
    valid = validate_outputs()
    if not valid:
        print("ERROR: Output validation failed!")
        sys.exit(1)

    print("\\n=== Daily Learning Loop Complete ===")
    return summary


if __name__ == "__main__":
    summary = main()
    print(f"\\nChange summary: {json.dumps(summary, ensure_ascii=False, indent=2)}")