#!/usr/bin/env python3
"""
Daily Learning Loop — 核心运行脚本

职责：
1. 读取 STATE.md、learning-state.json、最近日报、笔记、研究草稿、复习队列
2. 调用 LLM 生成今日日报、复习题与状态更新
3. 输出到 content/reports/daily/、content/dashboards/、state/、REVIEW-QUEUE.md、STATE.md

注意：本脚本不直接修改 .github/、scripts/、site/、skills/、prompts/、loop-* 文件。
"""

import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

# 项目根目录
REPO_ROOT = Path(__file__).resolve().parent.parent

# 路径常量
STATE_MD = REPO_ROOT / "STATE.md"
STATE_JSON = REPO_ROOT / "state" / "learning-state.json"
REVIEW_QUEUE_MD = REPO_ROOT / "REVIEW-QUEUE.md"
REVIEW_QUEUE_JSON = REPO_ROOT / "state" / "review-queue.json"
NOTES_DIR = REPO_ROOT / "content" / "notes"
RESEARCH_DIR = REPO_ROOT / "content" / "research"
DAILY_DIR = REPO_ROOT / "content" / "reports" / "daily"
DASHBOARDS_DIR = REPO_ROOT / "content" / "dashboards"
PROMPT_FILE = REPO_ROOT / "prompts" / "daily-learning-loop.prompt.md"
SKILL_FILE = REPO_ROOT / "skills" / "daily-learning-triage.md"


def read_file(path: Path) -> str:
    """安全读取文件内容，不存在时返回空字符串。"""
    if path.exists():
        return path.read_text(encoding="utf-8")
    return ""


def write_file(path: Path, content: str) -> None:
    """写入文件，自动创建父目录。"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def get_recent_daily_reports(days: int = 3) -> list[dict]:
    """获取最近 N 天的日报文件列表。"""
    if not DAILY_DIR.exists():
        return []
    files = sorted(DAILY_DIR.glob("*.md"), reverse=True)
    reports = []
    for f in files[:days]:
        reports.append({
            "path": str(f.relative_to(REPO_ROOT)),
            "content": f.read_text(encoding="utf-8") if f.exists() else ""
        })
    return reports


def build_context() -> dict:
    """构建 LLM 调用的完整上下文。"""
    # 读取笔记内容
    notes_content = ""
    if NOTES_DIR.exists():
        for f in sorted(NOTES_DIR.glob("*.md")):
            notes_content += f"\n---\n### {f.name}\n"
            notes_content += f.read_text(encoding="utf-8")

    # 读取研究草稿内容
    research_content = ""
    if RESEARCH_DIR.exists():
        for f in sorted(RESEARCH_DIR.glob("*.md")):
            research_content += f"\n---\n### {f.name}\n"
            research_content += f.read_text(encoding="utf-8")

    return {
        "state_md": read_file(STATE_MD),
        "state_json": read_file(STATE_JSON),
        "review_queue_md": read_file(REVIEW_QUEUE_MD),
        "review_queue_json": read_file(REVIEW_QUEUE_JSON),
        "recent_reports": get_recent_daily_reports(3),
        "notes_content": notes_content,
        "research_content": research_content,
        "skill": read_file(SKILL_FILE),
        "prompt_template": read_file(PROMPT_FILE),
        "current_date": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
    }


def build_messages(context: dict) -> tuple[str, str]:
    """
    组装 system prompt 和 user message。
    将 prompt 模板中的 {{date}} 替换为当前日期。
    """
    date_str = context["current_date"]
    prompt = context["prompt_template"]
    prompt = prompt.replace("{{date}}", date_str)

    # 提取 system prompt 和 user message 模板
    # 假设 prompt 模板以 "你是我的 Daily Learning Loop。" 开头为 system 部分
    # 以 "### 读取以下文件" 为 user message 起始
    system_prompt = prompt

    # 构建 user message，包含所有上下文数据
    user_msg = f"""当前日期：{date_str}

## 当前学习状态
{context['state_md']}

## 学习状态 JSON
{context['state_json']}

## 复习队列
{context['review_queue_md']}

## 笔记内容
{context['notes_content'] if context['notes_content'] else '(暂无笔记)'}

## 研究草稿
{context['research_content'] if context['research_content'] else '(暂无研究草稿)'}

## 最近日报
{chr(10).join(f'### {r["path"]}\n{r["content"]}' for r in context['recent_reports']) if context['recent_reports'] else '(暂无历史日报)'}

请根据以上信息，按照指令生成今日日报、复习队列更新和状态更新。
"""

    return system_prompt, user_msg


def call_llm(system_prompt: str, user_message: str) -> str:
    """
    通过 Anthropic 协议调用 LLM API。
    从环境变量读取 API 配置：
      - LLM_API_KEY: API 密钥
      - LLM_BASE_URL: API 基础地址
      - LLM_MODEL: 模型名称
    """
    # 去除可能存在的换行符或空格，避免 HTTP header 解析错误
    api_key = os.environ.get("LLM_API_KEY", "").strip()
    base_url = os.environ.get("LLM_BASE_URL", "https://ark.cn-beijing.volces.com/api/coding").strip()
    # 确保 base_url 末尾没有多余的斜杠
    if base_url.endswith("/"):
        base_url = base_url.rstrip("/")
    model = os.environ.get("LLM_MODEL", "DeepSeek-V4-Flash").strip()

    if not api_key:
        print("  WARNING: LLM_API_KEY not set, using placeholder output")
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        return f"""# Daily Learning Report — {date_str}

## Summary

This is a placeholder report. LLM API key not configured.

## Key Findings

- System is ready
- Waiting for API key to be configured in repository secrets

## Next Steps

1. Set LLM_API_KEY in GitHub repository secrets
2. Trigger the workflow again

---

> Generated by Daily Learning Loop on {date_str}
"""

    try:
        import httpx
        import json as json_module

        # 使用 httpx 直接调用
        headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {api_key}",
            "anthropic-version": "2023-06-01",
        }

        payload = {
            "model": model,
            "max_tokens": 8192,
            "system": system_prompt,
            "messages": [
                {"role": "user", "content": user_message}
            ],
        }

        # 组装请求 URL：Anthropic 协议消息接口路径为 /v1/messages
        request_url = f"{base_url}/v1/messages"

        print(f"  Request URL: {request_url}")
        print(f"  Model: {model}")
        print(f"  User message: {len(user_message)} chars")

        with httpx.Client(timeout=300.0) as client:
            response = client.post(
                request_url,
                headers=headers,
                json=payload,
            )

        if response.status_code != 200:
            print(f"  API Error: status={response.status_code}")
            print(f"  Response: {response.text[:500]}")
            response.raise_for_status()

        result = response.json()
        content = ""
        for block in result.get("content", []):
            if block.get("type") == "text":
                content += block.get("text", "")

        return content

    except ImportError:
        print("  ERROR: httpx package not installed. Run: pip install httpx")
        raise
    except Exception as e:
        print(f"  ERROR: LLM call failed: {e}")
        raise


def parse_output(output: str) -> dict:
    """
    解析 LLM 输出，提取变更摘要 JSON。
    如果输出末尾包含 JSON 摘要，则解析并返回；否则返回空摘要。
    """
    # 尝试从输出末尾提取 JSON
    json_match = re.search(r'```json\n(.+?)\n```', output, re.DOTALL)
    if json_match:
        try:
            return json.loads(json_match.group(1))
        except json.JSONDecodeError:
            pass
    return {
        "change_summary": "No structured summary available",
        "files_changed": [],
        "risk_level": "low",
        "new_review_items": 0,
        "archived_items": 0,
        "uncertain_claims": [],
        "sources_used": []
    }


def write_outputs(output: str, context: dict) -> dict:
    """将 LLM 输出写入对应的目标文件。"""
    date_str = context["current_date"]

    # 1. 写入今日日报
    daily_file = DAILY_DIR / f"{date_str}.md"
    write_file(daily_file, output)

    # 2. 写入今日仪表盘（简单提取第一段作为摘要）
    first_line = output.strip().split("\n")[0] if output.strip() else "No content"
    dashboard = f"""# Today's Dashboard

{first_line}

## Quick Stats

- Date: {date_str}
- Status: Report generated

## Recent Activity

{output}
"""
    dashboard_file = DASHBOARDS_DIR / "today.md"
    write_file(dashboard_file, dashboard)

    # 3. 解析变更摘要
    summary = parse_output(output)

    return summary


def validate_outputs() -> bool:
    """调用 validate_outputs.py 验证输出。"""
    import subprocess
    result = subprocess.run(
        [sys.executable, str(REPO_ROOT / "scripts" / "validate_outputs.py")],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(f"Validation failed:\\n{result.stderr}")
        return False
    print("Validation passed.")
    return True


def main():
    """Daily Learning Loop 主流程。"""
    print("=== Daily Learning Loop ===")
    print(f"Time: {datetime.now(timezone.utc).isoformat()}")

    # Step 1: 构建上下文
    print("\\n[1/5] Building context...")
    context = build_context()
    print(f"  Date: {context['current_date']}")
    print(f"  Notes: {len(context['notes_content'])} chars")
    print(f"  Research: {len(context['research_content'])} chars")

    # Step 2: 构建 system prompt 和 user message
    print("\\n[2/5] Building messages...")
    system_prompt, user_message = build_messages(context)
    print(f"  System prompt: {len(system_prompt)} chars")
    print(f"  User message: {len(user_message)} chars")

    # Step 3: 调用 LLM
    print("\\n[3/5] Calling LLM...")
    output = call_llm(system_prompt, user_message)
    print("\\n[3/5] Calling LLM...")
    output = call_llm(system_prompt, context)
    print(f"  Output length: {len(output)} chars")

    # Step 4: 写入输出
    print("\\n[4/5] Writing outputs...")
    summary = write_outputs(output, context)
    print(f"  Files changed: {summary.get('files_changed', [])}")
    print(f"  Risk level: {summary.get('risk_level', 'unknown')}")

    # Step 5: 验证输出
    print("\\n[5/5] Validating outputs...")
    valid = validate_outputs()
    if not valid:
        print("ERROR: Output validation failed!")
        sys.exit(1)

    print("\\n=== Daily Learning Loop Complete ===")
    return summary


if __name__ == "__main__":
    summary = main()
    print(f"\\nChange summary: {json.dumps(summary, ensure_ascii=False, indent=2)}")